name: CI

on:
  pull_request:
    types:
    - '*'
  push:
    branches:
    - master
    tags:
    - '*'


jobs:
  linux:
    strategy:
      matrix:
        pattern: [0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      shell: bash
      run: |
        clang --version
        gcc --version
        cc --version
        echo ${{ matrix.pattern }}
        if [ ${{ matrix.pattern }} == 0 ]; then MY=1 && echo ${MY}; fi
        if [ ${{ matrix.pattern }} == 1 ]; then echo "one"; fi
        if [ ${{ matrix.pattern }} == 2 ]; then echo "two"; fi
  macos:
    strategy:
      matrix:
        pattern: [0]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
  windows:
    strategy:
      matrix:
        pattern: [0]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: test1
      shell: bash
      run: |
        curl -O https://github.com/google/googletest/archive/release-1.7.0.zip
    - name: test2
      shell: powershell
      run: |
        echo "env:PATH"
        env:PATH="env:PATH;hoge"
        echo "env:PATH"
        echo env:PATH
        $VAR="hoge"
        echo VAR
        echo %VAR%
        echo $VAR
        echo "%VAR%"
        echo "$VAR"
        
        curl https://github.com/google/googletest/archive/release-1.7.0.zip
        curl -O https://github.com/google/googletest/archive/release-1.7.0.zip
        #bitsadmin //TRANSFER htmlget "https://github.com/google/googletest/archive/release-1.7.0.zip" "${BASE}/googletest-release-1.7.0.zip"
        
                
