name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        pattern: [0,1,2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      shell: bash
      run: |
        echo ${{ matrix.pattern }}
        if [ ${{ matrix.pattern }} == 0 ]; then echo "zero"; fi
        if [ ${{ matrix.pattern }} == 1 ]; then echo "one"; fi
        if [ ${{ matrix.pattern }} == 2 ]; then echo "two"; fi
        
