name: CI

on:
  pull_request:
    types:
    - '*'
  push:
    branches:
    - master
    tags:
    - '*'


jobs:
  linux:
    strategy:
      matrix:
        pattern: [0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      shell: bash
      run: |
        #sudo apt-get upgrade
        #sudo apt-get update
        sudo apt-get install gcc-multilib
        clang --version
        gcc --version
        cc --version
        echo ${{ matrix.pattern }}
        if [ ${{ matrix.pattern }} == 0 ]; then MY=1 && echo ${MY}; fi
        if [ ${{ matrix.pattern }} == 1 ]; then echo "one"; fi
        if [ ${{ matrix.pattern }} == 2 ]; then echo "two"; fi
  macos:
    strategy:
      matrix:
        pattern: [0]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
  windows:
    strategy:
      matrix:
        pattern: [0]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: test1
      shell: bash
      run: |
        curl -O https://github.com/google/googletest/archive/release-1.7.0.zip
    - name: test2
      shell: powershell
      run: |
        dir
        #$env:BOOST_ROOT="$env:BOOST_ROOT"
        echo $env:BOOST_ROOT
        echo "step1"
        md build
        echo "step2"
        cd build
        echo "step3"
        #cmake --version
        cmake ..\
        echo "step4"
